bcp szetav..aramkor out aramkor.txt /S10.1.1.1 /Usa /P /n
bcp szetav..arvalt out arvalt.txt /S10.1.1.1 /Usa /P /n
bcp szetav..biztonsagi_szelep out biztonsagi_szelep.txt /S10.1.1.1 /Usa /P /n
bcp szetav..boyler out boyler.txt /S10.1.1.1 /Usa /P /n
bcp szetav..csekk out csekk.txt /S10.1.1.1 /Usa /P /n
bcp szetav..demag_emelogep out demag_emelogep.txt /S10.1.1.1 /Usa /P /n
bcp szetav..dolgozo out dolgozo.txt /S10.1.1.1 /Usa /P /n
bcp szetav..epulet out epulet.txt /S10.1.1.1 /Usa /P /n
bcp szetav..erzekelo out erzekelo.txt /S10.1.1.1 /Usa /P /n
bcp szetav..fazisjavito_kondenzator out fazisjavito_kondenzator.txt /S10.1.1.1 /Usa /P /n
bcp szetav..fogyt out fogyt.txt /S10.1.1.1 /Usa /P /n
bcp szetav..fokapcsolo out fokapcsolo.txt /S10.1.1.1 /Usa /P /n
bcp szetav..frekvenciavalto out frekvenciavalto.txt /S10.1.1.1 /Usa /P /n
bcp szetav..futomu out futomu.txt /S10.1.1.1 /Usa /P /n
bcp szetav..gaznyomas_mero out gaznyomas_mero.txt /S10.1.1.1 /Usa /P /n
bcp szetav..gaznyomas_szabalyozo out gaznyomas_szabalyozo.txt /S10.1.1.1 /Usa /P /n
bcp szetav..gazveszely_jelzo out gazveszely_jelzo.txt /S10.1.1.1 /Usa /P /n
bcp szetav..grid_fejlec out grid_fejlec.txt /S10.1.1.1 /Usa /P /n
bcp szetav..hajtomu out hajtomu.txt /S10.1.1.1 /Usa /P /n
bcp szetav..hazak out hazak.txt /S10.1.1.1 /Usa /P /n
bcp szetav..hocserelo out hocserelo.txt /S10.1.1.1 /Usa /P /n
bcp szetav..hokozpont out hokozpont.txt /S10.1.1.1 /Usa /P /n
bcp szetav..hoosszegzo out hoosszegzo.txt /S10.1.1.1 /Usa /P /n
bcp szetav..jegyz out jegyz.txt /S10.1.1.1 /Usa /P /n
bcp szetav..kapcsolat out kapcsolat.txt /S10.1.1.1 /Usa /P /n
bcp szetav..kapcstab out kapcstab.txt /S10.1.1.1 /Usa /P /n
bcp szetav..karban out karban.txt /S10.1.1.1 /Usa /P /n
bcp szetav..karbterv out karbterv.txt /S10.1.1.1 /Usa /P /n
bcp szetav..kazan out kazan.txt /S10.1.1.1 /Usa /P /n
bcp szetav..kazanego out kazanego.txt /S10.1.1.1 /Usa /P /n
bcp szetav..kepv_tet out kepv_tet.txt /S10.1.1.1 /Usa /P /n
bcp szetav..kepvis out kepvis.txt /S10.1.1.1 /Usa /P /n
bcp szetav..kodleir out kodleir.txt /S10.1.1.1 /Usa /P /n
bcp szetav..kodszot out kodszot.txt /S10.1.1.1 /Usa /P /n
bcp szetav..koltsegmegoszto out koltsegmegoszto.txt /S10.1.1.1 /Usa /P /n
bcp szetav..kompresszor out kompresszor.txt /S10.1.1.1 /Usa /P /n
bcp szetav..kontir out kontir.txt /S10.1.1.1 /Usa /P /n
bcp szetav..lakas out lakas.txt /S10.1.1.1 /Usa /P /n
bcp szetav..langor out langor.txt /S10.1.1.1 /Usa /P /n
bcp szetav..lepcsohaz out lepcsohaz.txt /S10.1.1.1 /Usa /P /n
bcp szetav..melegviz_tarolo out melegviz_tarolo.txt /S10.1.1.1 /Usa /P /n
bcp szetav..mlaptab out mlaptab.txt /S10.1.1.1 /Usa /P /n
bcp szetav..motor out motor.txt /S10.1.1.1 /Usa /P /n
bcp szetav..munkalap out munkalap.txt /S10.1.1.1 /Usa /P /n
bcp szetav..objektum out objektum.txt /S10.1.1.1 /Usa /P /n
bcp szetav..permis out permis.txt /S10.1.1.1 /Usa /P /n
bcp szetav..szabalyozo_automatika out szabalyozo_automatika.txt /S10.1.1.1 /Usa /P /n
bcp szetav..szabalyozo_szelep out szabalyozo_szelep.txt /S10.1.1.1 /Usa /P /n
bcp szetav..szerelveny out szerelveny.txt /S10.1.1.1 /Usa /P /n
bcp szetav..szerzfej out szerzfej.txt /S10.1.1.1 /Usa /P /n
bcp szetav..szerztel out szerztel.txt /S10.1.1.1 /Usa /P /n
bcp szetav..szintkapcsolo out szintkapcsolo.txt /S10.1.1.1 /Usa /P /n
bcp szetav..szivattyu out szivattyu.txt /S10.1.1.1 /Usa /P /n
bcp szetav..szla_alt out szla_alt.txt /S10.1.1.1 /Usa /P /n
bcp szetav..szla_alt_tet out szla_alt_tet.txt /S10.1.1.1 /Usa /P /n
bcp szetav..szurok out szurok.txt /S10.1.1.1 /Usa /P /n
bcp szetav..tab403 out tab403.txt /S10.1.1.1 /Usa /P /n
bcp szetav..tab403_1 out tab403_1.txt /S10.1.1.1 /Usa /P /n
bcp szetav..tab404 out tab404.txt /S10.1.1.1 /Usa /P /n
bcp szetav..tab406 out tab406.txt /S10.1.1.1 /Usa /P /n
bcp szetav..tab407 out tab407.txt /S10.1.1.1 /Usa /P /n
bcp szetav..tab408 out tab408.txt /S10.1.1.1 /Usa /P /n
bcp szetav..tab413 out tab413.txt /S10.1.1.1 /Usa /P /n
bcp szetav..tarcsa out tarcsa.txt /S10.1.1.1 /Usa /P /n
bcp szetav..tartaly out tartaly.txt /S10.1.1.1 /Usa /P /n
bcp szetav..teljm out teljm.txt /S10.1.1.1 /Usa /P /n
bcp szetav..termalkut out termalkut.txt /S10.1.1.1 /Usa /P /n
bcp szetav..termelo_cso out termelo_cso.txt /S10.1.1.1 /Usa /P /n
bcp szetav..ventillator out ventillator.txt /S10.1.1.1 /Usa /P /n
bcp szetav..vizlagyito out vizlagyito.txt /S10.1.1.1 /Usa /P /n
bcp szetav..vizora out vizora.txt /S10.1.1.1 /Usa /P /n
